###get user
get http://localhost:4000/user-api/test-user

###get author
get http://localhost:4000/author-api/test-author

###get admin
get http://localhost:4000/admin-api/test-admin

###author registration 
post http://localhost:4000/author-api/register
Content-Type: application/json

{
    "role":"author",
    "username":"vikas",
    "password":"vikas",
    "email":"vikas@gmail.com"
}

###user registration
post http://localhost:4000/user-api/register
Content-Type: application/json

{
    "role":"user",
    "username":"vikas",
    "password":"vikas",
    "email":"vikas@gmail.com"
}

###userlogin
post http://localhost:4000/user-api/login
Content-Type: application/json

{
    "role":"user",
    "username":"vikas",
    "password":"vikas"
}

###authorlogin 
post http://localhost:4000/author-api/login
Content-Type: application/json

{
    "role":"author",
    "username":"vikas",
    "password":"vikas"
}

###add article by author

post http://localhost:4000/author-api/article
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa2FzIiwiaWF0IjoxNzExMDE0Mzg1LCJleHAiOjE3MTEwMTQ1MjV9.W5_zhN0iVFkORRRyH0qkuppmX2v0_ArnK6148_vS67o
Content-Type : application/json

{
    "articleId":"{{$timestamp}}",
    "title":"JavaScript basics",
    "category":"programming",
    "content":"asdf ;lkjasdf ;lkjfjslkjfjl",
    "dateOfCreation":"{{$datetime iso8601}}",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"vikas",
    "comments":[ ],
    "status":true
}

###read own articles by author
get http://localhost:4000/author-api/articles/vikas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa2FzIiwiaWF0IjoxNzExMDE0Mzg1LCJleHAiOjE3MTEwMTQ1MjV9.W5_zhN0iVFkORRRyH0qkuppmX2v0_ArnK6148_vS67o


###read all articles by user
get http://localhost:4000/user-api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa2FzIiwiaWF0IjoxNzExMDE0Mzg1LCJleHAiOjE3MTEwMTQ1MjV9.W5_zhN0iVFkORRRyH0qkuppmX2v0_ArnK6148_vS67o

###soft delete
put http://localhost:4000/author-api/articles/vikas/1711001114
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa2FzIiwiaWF0IjoxNzExMDE0Mzg1LCJleHAiOjE3MTEwMTQ1MjV9.W5_zhN0iVFkORRRyH0qkuppmX2v0_ArnK6148_vS67o
Content-Type: application/json

{
    "status":true
}

###get all articles by users
get http://localhost:4000/user-api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa2FzIiwiaWF0IjoxNzExMDE0Mzg1LCJleHAiOjE3MTEwMTQ1MjV9.W5_zhN0iVFkORRRyH0qkuppmX2v0_ArnK6148_vS67o

###edit article by author
put http://localhost:4000/author-api/article
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa2FzIiwiaWF0IjoxNzExMDE0Mzg1LCJleHAiOjE3MTEwMTQ1MjV9.W5_zhN0iVFkORRRyH0qkuppmX2v0_ArnK6148_vS67o
Content-Type: application/json

{
    "articleId":"1711002150",
    "title":"JavaScript basics part2",
    "category":"programming in js",
    "content":"asdf ;bkkhkjdddddlkjasdf ;lkjfjslkjfjl fhhsjf",
    //"dateOfCreation":"2024-03-21T06:05:14.057Z",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"suresh",
    //"comments":[ ],
    //"status":true   
}

###add comment by user
put http://localhost:4000/user-api/article/1711002150/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa2FzIiwiaWF0IjoxNzExMDE0Mzg1LCJleHAiOjE3MTEwMTQ1MjV9.W5_zhN0iVFkORRRyH0qkuppmX2v0_ArnK6148_vS67o
Content-Type: application/json

{
    "username":"suresh",
    "comment":"villian"
}